from ServiceCatalogAPI.media_services.knowledge.global_io import global_io
from ServiceCatalogAPI.media_services.knowledge.spotify import spotify
from ServiceCatalogAPI.media_services.knowledge.genius import genius