from ServiceCatalogAPI.media_services.music.global_io import global_io
from ServiceCatalogAPI.media_services.music.spotify import spotify
from ServiceCatalogAPI.media_services.music.apple_music import apple_music
from ServiceCatalogAPI.media_services.music.deezer import deezer
from ServiceCatalogAPI.media_services.music.youtube_music import youtube_music
